server:
  port: 8200

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/test
    platform: h2
    #初始化脚本
    schema: classpath:db/schema.sql
      #在浏览器中开启控制台
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2




mybatis:
  #mapping路径
  mapper-locations: classpath:mapping/*Mapper.xml
  #配置映射类所在的包名
  type-aliases-package: com.linjingc.configdemo.entity
  # 配置自动转换驼峰标识
  configuration:
    map-underscore-to-camel-case: true
